import { StyleSheet } from 'react-native';

export const onboardingArtStyles = StyleSheet.create({
  artCard: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 352,
    aspectRatio: 1,
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  blob: {
    position: 'absolute',
    borderRadius: 999,
  },
  cashBlobLeft: {
    width: 150,
    height: 150,
    left: -22,
    top: 42,
  },
  cashBlobRight: {
    width: 136,
    height: 136,
    right: -24,
    top: 28,
  },
  poster: {
    width: '72%',
    height: '72%',
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    justifyContent: 'space-between',
    boxShadow: '0 10px 28px rgba(0, 0, 0, 0.08)',
  },
  moneyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  moneyLineWide: {
    width: 88,
    height: 10,
    borderRadius: 999,
  },
  moneyDot: {
    width: 18,
    height: 18,
    borderRadius: 999,
  },
  moneyStack: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
    height: 86,
  },
  moneyTile: {
    flex: 1,
    borderRadius: 18,
    height: 52,
  },
  moneyTileTall: {
    flex: 1,
    borderRadius: 18,
    height: 78,
  },
  summaryCard: {
    borderRadius: 18,
    padding: 12,
    gap: 12,
  },
  summaryChip: {
    width: 68,
    height: 14,
    borderRadius: 999,
  },
  summaryBars: {
    gap: 8,
  },
  summaryBar: {
    width: '100%',
    height: 12,
    borderRadius: 999,
  },
  summaryBarShort: {
    width: '62%',
    height: 12,
    borderRadius: 999,
  },
  floatingBadge: {
    position: 'absolute',
    right: 26,
    bottom: 26,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  floatingBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  quizBlobTop: {
    width: 154,
    height: 154,
    top: -36,
    right: -16,
  },
  questionCard: {
    width: '76%',
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingVertical: 20,
    gap: 16,
    boxShadow: '0 10px 28px rgba(0, 0, 0, 0.08)',
  },
  questionBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  questionBadgeText: {
    fontSize: 12,
    fontWeight: '800',
  },
  questionLines: {
    gap: 8,
  },
  questionLineWide: {
    width: '88%',
    height: 12,
    borderRadius: 999,
  },
  questionLine: {
    width: '58%',
    height: 12,
    borderRadius: 999,
  },
  answerColumn: {
    gap: 10,
  },
  answerChoice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1.5,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  answerRadio: {
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 2,
  },
  answerRadioSelected: {
    width: 18,
    height: 18,
    borderRadius: 999,
  },
  answerText: {
    height: 12,
    flex: 1,
    borderRadius: 999,
  },
  answerTextSelected: {
    height: 12,
    width: '72%',
    borderRadius: 999,
  },
  floatingDotCluster: {
    position: 'absolute',
    left: 24,
    bottom: 24,
    width: 42,
    height: 42,
    borderRadius: 999,
    opacity: 0.18,
  },
  goldBlobLeft: {
    width: 140,
    height: 140,
    left: -30,
    top: 54,
  },
  goldBlobBottom: {
    width: 120,
    height: 120,
    right: -18,
    bottom: 10,
    opacity: 0.75,
  },
  goldCard: {
    width: '74%',
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 20,
    boxShadow: '0 10px 28px rgba(0, 0, 0, 0.08)',
  },
  goldHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  goldHeading: {
    width: 86,
    height: 12,
    borderRadius: 999,
  },
  goldSubheading: {
    width: 58,
    height: 10,
    borderRadius: 999,
    marginTop: 10,
  },
  goldCoin: {
    width: 44,
    height: 44,
    borderRadius: 999,
  },
  goldBars: {
    height: 98,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
  },
  goldBarTall: {
    flex: 1,
    borderRadius: 20,
    height: 92,
  },
  goldBarMedium: {
    flex: 1,
    borderRadius: 20,
    height: 68,
  },
  goldBarSmall: {
    flex: 1,
    borderRadius: 20,
    height: 48,
  },
  goalPill: {
    position: 'absolute',
    right: 24,
    bottom: 24,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    boxShadow: '0 8px 18px rgba(138, 100, 23, 0.12)',
  },
  goalPillText: {
    fontSize: 12,
    fontWeight: '700',
  },
});
